### ISSUE TITLE
error rebuild canvas on Windows

### ISSUE THREAD

**Issue by znzn007007** [electron/rebuild#1070]
OS: Windows 11 
electron: 19.0.6
canvas: 2.11.0

`
Canvas.obj : error LNK2019: ????????? "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cd
ecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v
8@@@std@@XZ),?? "void __cdecl parsePNGArgs(class v8::Local<class v8::Value>,struct PngClosure &)" (?parsePNGArgs@@YAXV?
$Local@VValue@v8@@@v8@@AEAUPngClosure@@@Z) ??????? [C:\work\joinchain\code\desktop\node_modules\canvas\build\canvas.vcx
proj]
CanvasRenderingContext2d.obj : error LNK2001: ????????? "__declspec(dllimport) public: class std::shared_ptr<class v8::
BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_p
tr@VBackingStore@v8@@@std@@XZ) [C:\work\joinchain\code\desktop\node_modules\canvas\build\canvas.vcxproj]
ImageData.obj : error LNK2001: ????????? "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> _
_cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStor
e@v8@@@std@@XZ) [C:\work\joinchain\code\desktop\node_modules\canvas\build\canvas.vcxproj]
C:\work\joinchain\code\desktop\node_modules\canvas\build\Release\canvas.node : fatal error LNK1120: 1 ?????????? [C:\wo
rk\joinchain\code\desktop\node_modules\canvas\build\canvas.vcxproj]
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\work\joinchain\code\desktop\node_modules\canvas'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1

Error: node-gyp failed to rebuild 'C:\work\joinchain\code\desktop\node_modules\canvas'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1

    at NodeGyp.rebuildModule (C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Rebuilder.rebuild (C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\rebuild.js:112:17)
    at async C:\work\joinchain\code\desktop\node_modules\electron-rebuild\lib\src\cli.js:158:9
`

Why and how to resolve it ?

**Comment by linqian02** [comment]
any progress?

**Comment by GitMurf** [comment]
This can now be closed with recent merged PR for node-canvas moving to the node-addon-api 🎉 https://github.com/Automattic/node-canvas/pull/2235

cc @znzn007007 @lqomg

**Comment by ImpChiang** [comment]
so, how to solve this error? @GitMurf @znzn007007

**Comment by TreehouseNorris** [comment]
see my answer https://github.com/Automattic/node-canvas/issues/1589#issuecomment-3005933997
